"""Add Tag model and many-to-many relationship

Revision ID: 4a225b85e3af
Revises: 2fafd22866d0
Create Date: 2014-11-08 19:10:52.923423

"""

# revision identifiers, used by Alembic.
revision = '4a225b85e3af'
down_revision = '2fafd22866d0'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tags',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tags_name'), 'tags', ['name'], unique=True)
    op.create_table('tags_rel',
    sa.Column('tag_id', sa.Integer(), nullable=True),
    sa.Column('document_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ),
    sa.ForeignKeyConstraint(['tag_id'], ['tags.id'], )
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tags_rel')
    op.drop_index(op.f('ix_tags_name'), table_name='tags')
    op.drop_table('tags')
    ### end Alembic commands ###
